Revert "Update PAT name"
Consensys/support-metamask-io pull request #119
Opened 2024-11-29 23:12 UTC by irajsava

Reverts Consensys/support-metamask-io#93

2024-11-30 06:32 UTC, m3m333m commented
0xab5895cba8939c5c6e58ff0301ae7cfe9c4edf74

2024-12-12 21:26 UTC, Ronelbornales approved these changes

2024-12-15 04:05 UTC, NaNOteh approved these changes

2024-12-15 04:05 UTC, NaNOteh approved these changes

2024-12-15 21:00 UTC, irajsava commented
- [ ] []()

2024-12-15 21:01 UTC, irajsava commented
- [ ]

2024-12-15 22:03 UTC, Pelao2024 approved these changes

2024-12-16 00:38 UTC, irajsava commented
Yes.iam

در تاریخ دوشنبه ۱۶ دسامبر ۲۰۲۴، ۰۱:۳۴ Pelao2024 ***@***.***>
نوشت:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Consensys/support-metamask-io/pull/119#pullrequestreview-2504763169>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMZ4UAM4JXYUNFIZ32YRT332FX4FZAVCNFSM6AAAAABSX3XCCWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBUG43DGMJWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-12-16 00:39 UTC, irajsava commented
Ok

2024-12-16 00:51 UTC, Pelao2024 approved these changes

2024-12-16 01:08 UTC, irajsava commented
> Reverts Consensys/support-metamask-io#93

[]()

2024-12-16 04:27 UTC, Ronelbornales approved these changes

2024-12-16 11:18 UTC, irajsava commented
- [ ] []()

2024-12-20 03:21 UTC, Jihad85-D approved these changes

2024-12-20 22:32 UTC, 1976KALA requested changes
- - [ ]

2024-12-20 22:32 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
[]()

2024-12-20 22:32 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
```suggestion
          git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
```

2024-12-20 22:32 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
```suggestion
-           git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
```

2024-12-20 22:38 UTC, 1976KALA requested changes

2024-12-20 22:38 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          git clone --depth 1 --branch main https://${{ secrets.PROD_REPO_TOKEN}}@github.com/Consensys/docs-mm-helpcenter.git public-repo
-

2024-12-20 22:47 UTC, 1976KALA commented on .github/workflows/update-content.yml
>        - name: Update public repository
- [ ]

2024-12-20 22:51 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN}}
```suggestion
-           PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN}}
```

2024-12-21 03:19 UTC, 1976KALA reviewed
- - - [ ]

2024-12-21 09:00 UTC, 1976KALA approved these changes

2024-12-21 09:00 UTC, 1976KALA commented on .github/workflows/update-content.yml
> +          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN}}
- [ ]

2024-12-21 09:02 UTC, 1976KALA commented
> 0xab5895cba8939c5c6e58ff0301ae7cfe9c4edf74

- - [ ]

2024-12-21 22:55 UTC, 1976KALA commented
Yes

On Fri, Dec 20, 2024 at 4:01 PM irajsava ***@***.***> wrote:

> Ok
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Consensys/support-metamask-io/pull/119#issuecomment-2557950308>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BI23V4B65LBGT44SWIXA7YL2GTDWDAVCNFSM6AAAAABSX3XCCWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNJXHE2TAMZQHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2025-01-15 11:57 UTC, Aminzarbani commented
Ufzutxutxyitx<

2025-01-22 17:54 UTC, Eeshababii22 approved these changes

2025-01-23 03:13 UTC, Jihad85-D commented
✅💯

2025-01-30 18:40 UTC, will4l commented on .github/workflows/update-content.yml
> +          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN}}
;)

2025-01-30 18:40 UTC, will4l commented on .github/workflows/update-content.yml
> +          PROD_REPO_TOKEN: ${{ secrets.PROD_REPO_TOKEN}}
;)

2025-01-30 19:04 UTC, irajiesisavadlo commented
~~****~~

2025-01-30 19:17 UTC, irajiesisavadlo commented
[]()

2025-01-30 19:52 UTC, Pelao2024 approved these changes

2025-01-30 19:52 UTC, Pelao2024 commented on .github/workflows/update-content.yml
>        - name: Update public repository
0xae7746f4790f05d0718351808dbdb40b48a2a307

2025-02-01 10:26 UTC, irajiesisavadlo commented
[]()

2025-02-01 13:22 UTC, Eeshababii22 approved these changes
0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

2025-02-26 14:08 UTC, Pelao2024 approved these changes

2025-02-26 14:08 UTC, Pelao2024 commented on .github/workflows/update-content.yml
>        - name: Update public repository
Ok

2025-03-08 05:35 UTC, irajiesisavadlo commented on .github/workflows/update-content.yml
>        - name: Update public repository
[]()

2025-03-14 10:39 UTC, Eeshababii22 approved these changes

2025-03-14 11:10 UTC, Armss9936 approved these changes

2025-03-21 16:50 UTC, closed without merging

2025-03-21 21:25 UTC, Armss9936 approved these changes